// flow-typed signature: 20cb747a6ecda40240d0acdd68bbb10b
// flow-typed version: <<STUB>>/@std/esm_v^0.25.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@std/esm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@std/esm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@std/esm/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module '@std/esm/esm.js' {
  declare module.exports: $Exports<'@std/esm/esm'>;
}
declare module '@std/esm/index' {
  declare module.exports: $Exports<'@std/esm'>;
}
declare module '@std/esm/index.js' {
  declare module.exports: $Exports<'@std/esm'>;
}
